### ISSUE TITLE
new_en2de

### ISSUE THREAD

**Issue by XDeepAzure** [longyuewangdcu/Document-MT-LLM#3]
你好，en2de的新闻数据集 [News Commentary v11](https://opus.nlpl.eu/News-Commentary-v11.php)，但是数据地址并没有提供test set 请问你的 测试数据是怎么得来的呢？

**Comment by zrustc** [comment]
我们参考先前篇章级别机器翻译论文（MCN、G-Trans等）的数据划分， newstest2015和newstest2016分别作为dev和test集，数据见：https://github.com/sameenmaruf/selective-attn
